### ISSUE TITLE
Destructing using only key breaks highlighting

### ISSUE THREAD

**Issue by wader** [bencampion/language-jq#2]
Example `def t: . as {$var} | $var;`:

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbencampion%2Flanguage-jq%2Fmaster%2Fgrammars%2Fjq.cson&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fstedolan%2Fjq%2Fmaster%2Fsrc%2Fbuiltin.jq&code=def+t%3A+.+as+%7B%24var%7D+%7C+%24var%3B

One solution is to add "#variable" pattern to "object" but it would make the highlighter allow object liberals like `{$var}` which is not valid jq syntax. I guess the proper solution is to somehow distinguish between a pattern and object literals.

**Comment by Alhadis** [comment]
Fixed in #4.
