### ISSUE TITLE
Array literal with more than one element inside object literal break highlighting

### ISSUE THREAD

**Issue by wader** [bencampion/language-jq#3]
Example: `def array_in_object: {abc: [1,2]};`

https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fbencampion%2Flanguage-jq%2Fmaster%2Fgrammars%2Fjq.cson&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fraw.githubusercontent.com%2Fstedolan%2Fjq%2Fmaster%2Fsrc%2Fbuiltin.jq&code=def+array_in_object%3A+%7Babc%3A+%5B1%2C2%5D%7D%3B

I'm trying to improve the syntax used by a vscode extension https://github.com/orentrutner/jq-syntax-highlighting 

My idea is to use your syntax with some small fixes, you can see the modified syntax here:
https://github.com/wader/jq-syntax-highlighting/blob/use-syntax-from-atom-jq/syntaxes/jq.tmLanguage.json

**Comment by Alhadis** [comment]
Fixed in #4.

NB: This wasn't closed automatically the way #1 was, because [when you wrote](https://github.com/wader/language-jq/pull/4#issue-584281369)

> Fixes #1 #2 #3

… GitHub only marked the first issue for auto-closing. A trick I use to work-around that is to use a wording like

> This PR fixes #1, fixes #2, and fixes #3.

Or even just

> Fixes: #1
> Fixes: #2
> Fixes: #3
